# Generated by Django 5.2.16 on 2026-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch'),
        ),
    ]
