# Generated by Django 5.2.16 on 2026-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teacher_academic_title_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_title',
            field=models.CharField(choices=[('Prof. Dr.', 'Prof. Dr.'), ('Assoc. Prof. Dr.', 'Assoc. Prof. Dr.'), ('Asst. Prof. Dr.', 'Asst. Prof. Dr.'), ('Lecturer', 'Lecturer'), ('Research Asst.', 'Research Asst.'), ('Teacher', 'Teacher')], default='Prof. Dr.', max_length=30, verbose_name='Academic Title'),
        ),
    ]
