# Generated by Django 5.2.16 on 2026-07-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teacher_academic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='building_wing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faculty Building / Wing'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=50, verbose_name='Seating Capacity'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='has_air_con',
            field=models.BooleanField(default=False, verbose_name='Has Air Conditioning'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='has_projector',
            field=models.BooleanField(default=True, verbose_name='Has Smartboard / Projector'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Room Code / Number'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('Lecture Hall / Amphi', 'Lecture Hall / Amphi'), ('Computer Laboratory', 'Computer Laboratory'), ('Science Laboratory', 'Science Laboratory'), ('Seminar Room', 'Seminar Room'), ('Standard Classroom', 'Standard Classroom')], default='Standard Classroom', max_length=30, verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective'), ('General Requirement', 'General Requirement')], default='Compulsory', max_length=30, verbose_name='Course Type'),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=6, verbose_name='ECTS Credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faculty / Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_block_hours',
            field=models.IntegerField(default=2, verbose_name='Max Block Hours'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='academic_year',
            field=models.CharField(choices=[('Year 1 (Freshman)', 'Year 1 (Freshman)'), ('Year 2 (Sophomore)', 'Year 2 (Sophomore)'), ('Year 3 (Junior)', 'Year 3 (Junior)'), ('Year 4 (Senior)', 'Year 4 (Senior)')], default='Year 1 (Freshman)', max_length=30, verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_classes', to='api.teacher', verbose_name='Academic Advisor'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='degree_level',
            field=models.CharField(choices=[('Bachelor (B.Sc.)', 'Bachelor (B.Sc.)'), ('Master (M.Sc.)', 'Master (M.Sc.)'), ('Doctorate (Ph.D.)', 'Doctorate (Ph.D.)'), ('Associate (A.A.)', 'Associate (A.A.)')], default='Bachelor (B.Sc.)', max_length=30, verbose_name='Degree Level'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='home_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Building / Campus'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='student_count',
            field=models.IntegerField(default=40, verbose_name='Student Count / Capacity'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='is_lab',
            field=models.BooleanField(default=False, verbose_name='Is Laboratory Facility?'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Hall / Room Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_lab_required',
            field=models.BooleanField(default=False, verbose_name='Requires Laboratory Facility'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Course Title'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cohort / Section Name'),
        ),
    ]
