# Generated by Django 5.2.16 on 2026-07-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_classroom_building_wing_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='building_wing',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='has_air_con',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='has_projector',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='room_code',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Room / Hall Name'),
        ),
    ]
